In [33]:
import numpy as np
from netCDF4 import Dataset
import os
import re

In [7]:
data = Dataset('data/OR_ABI-L1b-RadF-M6C07_G17_s20192210000339_e20192210009416_c20192210009459.nc')

In [15]:
print(data.variables.keys())

odict_keys(['Rad', 'DQF', 't', 'y', 'x', 'time_bounds', 'goes_imager_projection', 'y_image', 'y_image_bounds', 'x_image', 'x_image_bounds', 'nominal_satellite_subpoint_lat', 'nominal_satellite_subpoint_lon', 'nominal_satellite_height', 'geospatial_lat_lon_extent', 'yaw_flip_flag', 'band_id', 'band_wavelength', 'esun', 'kappa0', 'planck_fk1', 'planck_fk2', 'planck_bc1', 'planck_bc2', 'valid_pixel_count', 'missing_pixel_count', 'saturated_pixel_count', 'undersaturated_pixel_count', 'focal_plane_temperature_threshold_exceeded_count', 'min_radiance_value_of_valid_pixels', 'max_radiance_value_of_valid_pixels', 'mean_radiance_value_of_valid_pixels', 'std_dev_radiance_value_of_valid_pixels', 'maximum_focal_plane_temperature', 'focal_plane_temperature_threshold_increasing', 'focal_plane_temperature_threshold_decreasing', 'percent_uncorrectable_L0_errors', 'earth_sun_distance_anomaly_in_AU', 'algorithm_dynamic_input_data_container', 'processing_parm_version_container', 'algorithm_product_versio

In [16]:
print(data.variables)

OrderedDict([('Rad', <class 'netCDF4._netCDF4.Variable'>
int16 Rad(y, x)
    _FillValue: 16383
    long_name: ABI L1b Radiances
    standard_name: toa_outgoing_radiance_per_unit_wavenumber
    _Unsigned: true
    sensor_band_bit_depth: 14
    valid_range: [    0 16382]
    scale_factor: 0.001564351
    add_offset: -0.0376
    units: mW m-2 sr-1 (cm-1)-1
    resolution: y: 0.000056 rad x: 0.000056 rad
    coordinates: band_id band_wavelength t y x
    grid_mapping: goes_imager_projection
    cell_methods: t: point area: point
    ancillary_variables: DQF
unlimited dimensions: 
current shape = (5424, 5424)
filling on), ('DQF', <class 'netCDF4._netCDF4.Variable'>
int8 DQF(y, x)
    _FillValue: -1
    long_name: ABI L1b Radiances data quality flags
    standard_name: status_flag
    _Unsigned: true
    valid_range: [0 4]
    units: 1
    coordinates: band_id band_wavelength t y x
    grid_mapping: goes_imager_projection
    cell_methods: t: point area: point
    flag_values: [0 1 2 3 4]
  

In [54]:
files = [f for f in os.listdir('data/') if re.match(r'.*\.npy', f)]
G16_files = [f for f in files if re.match(r'.*_G16_.*', f)]
G17_files = [f for f in files if re.match(r'.*_G17_.*', f)]

[print(f) for f in G16_files]
print('\n')
[print(f) for f in G17_files]

fall_npy_221_OR_ABI-L1b-RadF-M6C07_G16_s20192210000548_e20192210010268_c20192210010328.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G16_s20192210010548_e20192210020268_c20192210020332.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G16_s20192210020548_e20192210030268_c20192210030328.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G16_s20192210030548_e20192210040268_c20192210040326.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G16_s20192210040549_e20192210050269_c20192210050323.npy


fall_npy_221_OR_ABI-L1b-RadF-M6C07_G17_s20192210000339_e20192210009416_c20192210009459.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G17_s20192210010339_e20192210019417_c20192210019461.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G17_s20192210020339_e20192210029417_c20192210029462.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G17_s20192210030339_e20192210039417_c20192210039464.npy
fall_npy_221_OR_ABI-L1b-RadF-M6C07_G17_s20192210040339_e20192210049417_c20192210049462.npy


[None, None, None, None, None]

In [59]:
G16_data = [np.load('data/'+data) for data in G16_files]
G17_data = [np.load('data/'+data) for data in G17_files]

print('G16 data shape: ',G16_data[0].shape)
print('G17 data shape: ',G17_data[0].shape)

G16 data shape:  (1001, 401)
G17 data shape:  (1001, 401)


In [61]:
G16_data[0]

array([[0.7789913 , 0.7680408 , 0.7226746 , ..., 0.50835854, 0.56780386,
        0.62881356],
       [0.7789913 , 0.7226746 , 0.70233804, ..., 0.53808117, 0.5990909 ,
        0.6460214 ],
       [0.7508329 , 0.70233804, 0.70233804, ..., 0.5803187 , 0.64445704,
        0.65540755],
       ...,
       [0.07503328, 0.06564717, 0.06564717, ..., 0.8665949 , 0.8634662 ,
        0.8587732 ],
       [0.07816197, 0.06095411, 0.06564717, ..., 0.8055852 , 0.7742982 ,
        0.79776347],
       [0.07816197, 0.06877588, 0.06095411, ..., 0.68982327, 0.70546675,
        0.7508329 ]], dtype=float32)

In [60]:
G17_data[0]

array([[0.71172416, 0.6632293 , 0.6366353 , ..., 0.5349525 , 0.51148725,
        0.5881404 ],
       [0.6757441 , 0.62568486, 0.639764  , ..., 0.55528903, 0.5349525 ,
        0.5881404 ],
       [0.6647936 , 0.61317   , 0.6209918 , ..., 0.55528903, 0.55528903,
        0.59596217],
       ...,
       [0.03123144, 0.02810274, 0.0296671 , ..., 0.7539616 , 0.7539616 ,
        0.7211103 ],
       [0.0296671 , 0.0296671 , 0.0296671 , ..., 0.7539616 , 0.6960806 ,
        0.65384316],
       [0.0296671 , 0.02810274, 0.02810274, ..., 0.6960806 , 0.6116057 ,
        0.65384316]], dtype=float32)

In [112]:
diff = abs(G16_data[0] - G17_data[0])
#std of total group

n16 = G16_data[0].shape[0] * G16_data[0].shape[1]
n17 = G17_data[0].shape[0] * G17_data[0].shape[1]
var16 = np.var(G16_data[0])
var17 = np.var(G17_data[0])
mean16 = np.mean(G16_data[0])
mean17 = np.mean(G17_data[0])

mean = (n16*mean16+n17*mean17)/(n16+n17)
d16 = mean16 - mean
d17 = mean17 - mean
std = np.sqrt((n16*(var16**2 + d16**2) + n17*(var17**2 + d17**2))/(n16+n17))
print(std)

0.03642378705444459


In [113]:
diff

array([[0.06726712, 0.10481149, 0.0860393 , ..., 0.02659398, 0.05631661,
        0.04067314],
       [0.10324717, 0.09698975, 0.06257403, ..., 0.01720786, 0.06413835,
        0.057881  ],
       [0.0860393 , 0.08916801, 0.08134621, ..., 0.02502966, 0.08916801,
        0.05944538],
       ...,
       [0.04380183, 0.03754443, 0.03598007, ..., 0.11263329, 0.10950458,
        0.13766289],
       [0.04849487, 0.03128701, 0.03598007, ..., 0.05162358, 0.07821757,
        0.1439203 ],
       [0.04849487, 0.04067313, 0.03285137, ..., 0.00625736, 0.09386104,
        0.09698975]], dtype=float32)

In [114]:
flags = np.ceil(diff/std)
flags

array([[2., 3., 3., ..., 1., 2., 2.],
       [3., 3., 2., ..., 1., 2., 2.],
       [3., 3., 3., ..., 1., 3., 2.],
       ...,
       [2., 2., 1., ..., 4., 4., 4.],
       [2., 1., 1., ..., 2., 3., 4.],
       [2., 2., 1., ..., 1., 3., 3.]], dtype=float32)

In [79]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [81]:
X_train, X_test, y_train, y_test = train_test_split(G17_data[0], flags, test_size=0.2, random_state=42)

In [82]:
clf = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=None, min_samples_split=2, 
                             min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', 
                             max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, 
                             bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, 
                             warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)
clf.fit(X_train, y_train)
print(clf.feature_importances_)

[0.0024458  0.00289156 0.00231973 0.00296266 0.00268551 0.00240928
 0.00272515 0.00256565 0.00214921 0.00274761 0.00313286 0.00352562
 0.00252139 0.00202172 0.00247852 0.00249933 0.00227783 0.00267746
 0.00224262 0.00210555 0.0021332  0.00275688 0.00178113 0.00210366
 0.00178935 0.00183475 0.00213017 0.00187618 0.00209566 0.00289585
 0.00244805 0.00196509 0.00199184 0.00209207 0.0021328  0.00221609
 0.00196878 0.00262558 0.00248093 0.0020847  0.00270886 0.00269637
 0.0024686  0.0026124  0.00192207 0.00297888 0.00200247 0.00260428
 0.0026439  0.00267242 0.00286971 0.00235477 0.00248645 0.00285983
 0.00254832 0.00251768 0.00250124 0.00239521 0.00281387 0.00269361
 0.00211302 0.00236726 0.00242742 0.00234623 0.00220727 0.0030476
 0.00307034 0.00272875 0.00219871 0.00214263 0.00274679 0.0020766
 0.00240699 0.00178955 0.00283356 0.00229552 0.00257763 0.0023908
 0.00235352 0.00226178 0.00150373 0.00216715 0.00191621 0.00242949
 0.00203741 0.00219239 0.00227829 0.00250874 0.00257298 0.0017462

In [111]:
predict = clf.predict(X_test)

In [126]:
from sklearn.metrics import mean_squared_error
errors = abs(predict - y_test)
print('test')
print('Mean Absolute Error:', round(np.mean(abs(predict - y_test)), 2))
print('Mean Squared Error:', mean_squared_error(y_test, predict))

train_predict = clf.predict(X_train)
print('train')
print('Mean Absolute Error:', round(np.mean(abs(train_predict - y_train)), 2))
print('Mean Squared Error:', mean_squared_error(y_train, train_predict))


test
Mean Absolute Error: 0.35
Mean Squared Error: 0.50850487
train
Mean Absolute Error: 0.0


ValueError: Found input variables with inconsistent numbers of samples: [201, 800]

In [129]:
print('Mean Squared Error:', mean_squared_error(y_train, train_predict))

Mean Squared Error: 2.1820446e-05


In [122]:
diff = abs(G16_data[1] - G17_data[1])
#std of total group

n16 = G16_data[1].shape[0] * G16_data[1].shape[1]
n17 = G17_data[1].shape[0] * G17_data[1].shape[1]
var16 = np.var(G16_data[1])
var17 = np.var(G17_data[1])
mean16 = np.mean(G16_data[1])
mean17 = np.mean(G17_data[1])

mean = (n16*mean16+n17*mean17)/(n16+n17)
d16 = mean16 - mean
d17 = mean17 - mean
std = np.sqrt((n16*(var16**2 + d16**2) + n17*(var17**2 + d17**2))/(n16+n17))
print(std)
flags2 = np.ceil(diff/std)

0.03585463437446557


In [123]:
predict2 = clf.predict(G17_data[1])

In [124]:
errors2 = abs(predict2 - flags2)
print('Mean Absolute Error:', round(np.mean(errors2), 2), 'degrees.')
print(mean_squared_error(predict2, y_test))
print(mean_squared_error(flag2, predict2))

Mean Absolute Error: 0.54 degrees.


ValueError: Found input variables with inconsistent numbers of samples: [1001, 201]

In [105]:
from sklearn.ensemble import BaggingRegressor

abr = BaggingRegressor(base_estimator=None, n_estimators=10, max_samples=1.0, max_features=1.0, 
                        bootstrap=True, bootstrap_features=False, oob_score=False, warm_start=False, 
                        n_jobs=None, random_state=None, verbose=0)
abr.fit(X_train, y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [106]:
predict = clf.predict(X_test)

In [107]:
errors = abs(predict - y_test)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.35 degrees.


In [108]:
predict2 = abr.predict(G17_data[1])
errors2 = abs(predict2 - flags2)
print('Mean Absolute Error:', round(np.mean(errors2), 2), 'degrees.')

Mean Absolute Error: 0.62 degrees.
